curl --request GET \
     --url 'https://api.themoviedb.org/3/movie/tt27557289' \
     --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5NjUxMjUzMWU1YWZlYjIzMmRlOWE2MzEzMTQ3MWNiZCIsIm5iZiI6MTc4MDQ2MjIyMi4xMjk5OTk5LCJzdWIiOiI2YTFmYjI4ZWRkMDNiNTFmYjFiYTY5ZmQiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.Oj-B43LWvH0pe6gw7iZKZQsmj3LLeyyRMzjPt4EVqf4'

curl "https://api.themoviedb.org/3/tv/76479?api_key=96512531e5afeb232de9a63131471cbd"